name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  run-linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run lint
