name: Unittests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/chrome/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
